### ISSUE TITLE
[Windows] npm install thows WARNINGS/ERROR

### ISSUE THREAD

**Issue by eriknyk** [zeit/hyper#1053]
```
λ npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> electron-chromedriver@1.4.0 install C:\Users\erik\Applications\hyper\node_modules\electron-chromedriver
> node ./download-chromedriver.js


> husky@0.11.9 install C:\Users\erik\Applications\hyper\node_modules\husky
> node ./bin/install.js

husky
setting up hooks in .git/hooks
done


> spawn-sync@1.0.15 postinstall C:\Users\erik\Applications\hyper\node_modules\spawn-sync
> node postinstall


> electron@1.4.7 postinstall C:\Users\erik\Applications\hyper\node_modules\electron
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\erik\Applications\hyper\node_modules\single-line-log\index.js:12:16)
    at process.<anonymous> (C:\Users\erik\Applications\hyper\node_modules\single-line-log\index.js:17:29)
    at emitOne (events.js:101:20)
```
- [x] I am on the branch `master`
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: branch `master`

**Comment by stefanivic** [comment]
@eriknyk Try updating your Node version to 7.2.

**Comment by ppot** [comment]
This is more related to npm than Hyper.
@matheuss
