### ISSUE TITLE
Unable to launch hyper 1.0.0 even after reinstall in Ubuntu 14.04

### ISSUE THREAD

**Issue by thekalinga** [zeit/hyper#1136]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux idealx 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux, Ubuntu 14.04
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Same as the default generated, no changes have been made, no plugins added
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When I try to launch hyper, I get the following error & terminal window is not launched

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, lstat '/home/<user>/�j[@@8@@@�r'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:292:14)
    at Gaze.add (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:190:8)
    at new Gaze (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:86:10)
    at watch (/opt/Hyper/resources/app/config.js:26:3)
    at Object.exports.init (/opt/Hyper/resources/app/config.js:102:3)
    at Object.<anonymous> (/opt/Hyper/resources/app/index.js:51:8)
```

**Comment by caiocutrim** [comment]
same here

**Comment by Tanmayshetty** [comment]
Maybe this is an issue with [Gaze](https://github.com/shama/gaze) .

shama/gaze#214

I never got past this error from the previous releases.

I built the application manually after changing **dirname** variable in **gaze.js** in node_modules folder and it works.

```
    var readdir = fs.readdirSync(dirname);  //Change here - Add Current Folder
    for (var j = 0; j < readdir.length; j++) {
      var dirfile = path.join(dirname, readdir[j]);
      if (fs.lstatSync(dirfile).isDirectory()) {
        helper.objectPush(this._watched, dirname, dirfile + path.sep);
      }
    }
```

**Comment by caiocutrim** [comment]
I don't know how to change this in gaze.js and not to rebuild manually :( in the version 1.0.1 of the hyper still not working and report the same error from gaze

-caio  /opt/Hyper 
$ ./hyper 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, lstat '/home/caio/�'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:292:14)
    at Gaze.add (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:190:8)
    at new Gaze (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/opt/Hyper/resources/app/node_modules/gaze/lib/gaze.js:86:10)
    at watch (/opt/Hyper/resources/app/config.js:26:3)
    at Object.exports.init (/opt/Hyper/resources/app/config.js:103:3)
    at Object.<anonymous> (/opt/Hyper/resources/app/index.js:51:8)

**Comment by caiocutrim** [comment]
how can I change and what I need to put in this dirname? Sorry for this noob question I'm trying to fix, but I can't understand this part of code.

**Comment by caiocutrim** [comment]
I change the snippet that was posted for you, and to date it works but closes immediately .

**Comment by caiocutrim** [comment]
It works, it was closed immediately because it founds the hyper_plugins directory and crashes, by fixing that it is necessary removing the plugins directory and run again.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
