### ISSUE TITLE
npm run app caught Error: Cannot find module 'git-describe'

### ISSUE THREAD

**Issue by bakso** [zeit/hyper#1158]
I git clone from the master and have executed npm intall .
Then I executed npm run dev in a terminal window and excuted npm run app in an another window, I caught a error below:

```shell
npm run app

> @ app /Users/bakso/dev/project/hyper
> electron app

App threw an error during load
Error: Cannot find module 'git-describe'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/bakso/dev/project/hyper/node_modules/.1.4.7@electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bakso/dev/project/hyper/app/index.js:33:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by ppot** [comment]
@bakso do an `sudo rm -rf` on the node_modules and then reinstall with `npm install`.
