### ISSUE TITLE
Latest Windows build throws up spawn UNKNOWN errors.

### ISSUE THREAD

**Issue by SirTimmyTimbit** [zeit/hyper#1303]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64
- **Node version:** 7.3.0
- **NPM version:** 4.0.5
- **Hyper.app version**: 1.0.364, built from Master
- **Link of a [Gist](https://gist.github.com/SirTimmyTimbit/ea669910a8057a0ceda258bd8a1d5d0b) with the contents of your .hyper.js**: [Gist](https://gist.github.com/SirTimmyTimbit/ea669910a8057a0ceda258bd8a1d5d0b)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A as app doesn't launch
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue
I built Hyper on Windows from the master branch, latest commit https://github.com/zeit/hyper/commit/f2ffafbd10a26489539db0fdd2cee1201f8b8528. **The dev app instance ran just fine**. but the generated binaries do not show the Hyper window when ran. I can see the app instance in task manager, and I can see the toast notifications too but the app window is not there. 

I tried the binary generated by [AppVeyor](https://ci.appveyor.com/project/appveyor-zeit/hyper), but it's the same result. 

When Hyper.exe is  ran from the command prompt I get this error:

```
C:\Users\dev\AppData\Local\hyper\app-1.0.1>Hyper.exe

C:\Users\dev\AppData\Local\hyper\app-1.0.1>
running in prod mode
electron will open file://C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\app\index.html
Checking for notification messages
No matching notification messages
Error fetching updates Error: spawn UNKNOWN (Error: Error: spawn UNKNOWN
    at AutoUpdater.emitError (C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.download (C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:43:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9))
```

## Edit

I built again after disabling auto updater in /app/index.js. It built and installed fine. The problem is still there, still don't see the Hyper window but this is the output now in command prompt:

```
C:\Users\dev\AppData\Local\hyper\app-1.0.1>
running in prod mode
electron will open file://C:\Users\dev\AppData\Local\hyper\app-1.0.1\resources\app\index.html
Checking for notification messages
No matching notification messages
```

just uninstalled this and installed the official Hyper 1.0.0 binary and it works just fine.

## Edit 2

Building and installing 1.0.0 release works just fine as well. Something broke along the way since then.

## Edit 3
Fixed the issue. It's because of  https://github.com/zeit/hyper/commit/ef5caeeb091cc7e8a823606f86e7aa8524645e40

**Comment by SirTimmyTimbit** [comment]
Fixed with https://github.com/zeit/hyper/commit/5773a83dc3211bd76efe4803176ab8b3df4a14be
