### ISSUE TITLE
Can't install dependencies.

### ISSUE THREAD

**Issue by NileshPS17** [zeit/hyper#1310]
I was trying to setup the project in my linux system but i get this.
What could be the issue?

**Error: /usr/bin/nodejs exited with code 1
Error output:
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/share/npm/bin/npm-cli.js" "install" "--production" "--cache-min" "999999999" "--build-from-source"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: gaze@1.1.2
npm ERR! Valid install targets:
npm ERR! 1.1.1, 1.1.0, 1.0.0, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nilesh/Projects/hyper/app/npm-debug.log

    at ChildProcess.childProcess.once.code (/home/nilesh/Projects/hyper/node_modules/electron-builder/src/util/util.ts:124:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/home/nilesh/Projects/hyper/node_modules/electron-builder/src/util/util.ts:87:3)
    at installDependencies (/home/nilesh/Projects/hyper/node_modules/electron-builder/src/yarn.ts:65:3)
    at /home/nilesh/Projects/hyper/node_modules/electron-builder/src/yarn.ts:11:11
    at next (native)
From previous event:
    at installOrRebuild (/home/nilesh/Projects/hyper/node_modules/electron-builder/out/yarn.js:33:21)
    at /home/nilesh/Projects/hyper/node_modules/electron-builder/src/install-app-deps.ts:29:2
    at next (native)
From previous event:
    at main (/home/nilesh/Projects/hyper/node_modules/electron-builder/out/install-app-deps.js:27:21)
    at Object.<anonymous> (/home/nilesh/Projects/hyper/node_modules/electron-builder/out/install-app-deps.js:73:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `install-app-deps`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'install-app-deps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nilesh/Projects/hyper/npm-debug.log**

**Comment by albinekb** [comment]
Looks like gaze@1.1.2 is released https://github.com/shama/gaze/releases/tag/v1.1.2
Try upgrading your node version perhaps?

**Comment by NileshPS17** [comment]
But i have node v6.9.2 and npm 4.0.5

**Comment by Tyriar** [comment]
I'm hitting this too on ea8a32d

Ubuntu 16.10
node 6.9.2
npm 3.8.5

**Comment by chabou** [comment]
Did you try with `yarn`?

**Comment by mackelito** [comment]
Using yarn install worked for me... npm install did not :)

**Comment by CodeTheory** [comment]
Is this still an issue @NileshPS @Tyriar? Would like to close due to inactivity if not.
