### ISSUE TITLE
Plugins not loading.

### ISSUE THREAD

**Issue by AlanPBourke** [zeit/hyper#1395]
Just updated to Hyper 1.1.0 on Windows 7 x64. Prior version was working fine. Now plugins are not working and throwing an npm error. 

Have tried:

- Deleting .hyper_plugins and updating Node. Running `node install` from within .hyper_plugins does the same thing.
- Uninstall, delete .hyper.js and plugins folder, reinstall.
[npm-debug-log.txt](https://github.com/zeit/hyper/files/702131/npm-debug-log.txt)

Hyper 1.1.0
Electron 1.4.7
win32 x64 6.1.7601

**Comment by tehbilly** [comment]
Same issue with Win10. `systeminformation` appears to be the culprit for me:

```
npm ERR! notsup Unsupported platform for systeminformation@3.13.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by matheuss** [comment]
@AlanPBourke @tehbilly which plugin(s) were you trying to install?

**Comment by AlanPBourke** [comment]
Hyperline and Hyperblue.

**Comment by chabou** [comment]
Hyperline is not compatible with Windows. Remove it :)

**Comment by gluons** [comment]
I just add [`hyper-snazzy`](https://github.com/sindresorhus/hyper-snazzy) in `plugins` but I see nothing in **.hyper_plugins** folder (have only `package.json` file).

**Comment by belthesar** [comment]
I get this when trying to add a plugin to Hyper 1.1.0. 

```
Error: Command failed: npm prune && npm install --production
/bin/bash: /s: No such file or directory

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.
```

Hyper: 1.1.0 on Windows 10 15014

**Comment by gluons** [comment]
@belthesar Oh! Thanks.
Now I understand why it doesn't work. I'm using **PowerShell** as my `shell`.

**Comment by SpencerLynn** [comment]
+1 I'm also using PowerShell and am having issues with plugins installing when I add them. I'm having to manually go to the `~/.hyper_plugins` folder and run `npm install`. Even occasionally having to manually add the plugin to the `package.json` file in that directory.

**Comment by cd-rum** [comment]
I'm on macOS and I had to go to `/.hyper_plugins` and run `npm -g install` to get my plugins installed. I reckon it's owning to the fact that I use non-system (i.e., `nvm`-managed Node).

**Comment by chabou** [comment]
@cd-rum what id your npm version ? We have some compatibilty issues with npm@5 (fixed in master)

**Comment by cd-rum** [comment]
@chabou That could be it, too. Using `5.0.3`.

**Comment by F21** [comment]
I am also seeing this problem, but I am using `cmd` instead of `powershell` on Windows 10 64-bit with latest updates. Hyper is 1.3.3 and Node is 8.1.2. I've tried installing things through `hpm`, and it successfully reloads, but the plugin fails to load.

Things I tried to install:
- https://www.npmjs.com/package/hyperterm-monokai
- https://www.npmjs.com/package/hypertheme
