### ISSUE TITLE
As a Windows Hyper user, I should be able to install packages regardless of which shell I am using

### ISSUE THREAD

**Issue by belthesar** [zeit/hyper#1480]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 build 15014
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/belthesar/b8a8f608a5ed47becd96068706eb6648
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue

Problem:  When running a shell other than 'cmd' on Windows, packages do not install successfully.  
Steps to Reproduce:  

1. With a functional Hyper install (vanilla, or with packages installed), modify your .hyper.js config to change the shell to a different shell (EG: "C:\\Windows\\System32\\bash.exe" or "%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe"). 
2. Add or remove packages.

Expected Result:  

Packages are installed or uninstalled as requested by adjusting the config. 

Actual Result:  

Packages are not installed.  Error suggest to look at %userprofile%\.hyper_plugins\npm-debug.log
This log file is never generated.  

Additional info:  Running Hyper within a cmd window provides additional logging that suggests that there is some sort of hard coding that is attempting to run whatever the current shell is with switches that only work with 'cmd'.  

'''
plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file://C:\Users\belthesar\AppData\Local\hyper\app-1.1.0\resources\app\index.html
Checking for notification messages
No matching notification messages
Error: Command failed: npm prune && npm install --production
/bin/bash: /s: No such file or directory

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.
'''

**Comment by gluons** [comment]
Me too. I'm using PowerShell. I can't install any package.

**Comment by srimajji** [comment]
I remember reading a temp fix in a different PR. 

Comment this [line in plugins.js](https://github.com/zeit/hyper/blob/master/app/plugins.js#L249).
Restart hyper and try to install any hyper package

**Comment by jordansjones** [comment]
@srimajji That does fix the issue. 

The problem is [Node's `child_process.exec`](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) requires the shell passed in the `shell` parameter to support the `-c` switch on UNIX and `/s /c` on Windows.

**Comment by belthesar** [comment]
@jordansjones Agreed with this recommendation.  Unless there's a need to preserve environment, which I can't see, lowest common denominator shell execution seems like the preferred behavior across all platforms.
