### ISSUE TITLE
Unable to run Hyper 1.1.0 on macOS

### ISSUE THREAD

**Issue by athyuttamre** [zeit/hyper#1499]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.2.2
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/athyuttamre/f65248a0eb40d544f36bf4a4f8b4ea2c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A, window doesn't launch
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

I'm unable to run Hyper on first install. I've never used Hyper before and just downloaded it from the website. Here's the error I get

```
A JavaScript error occurred in the main thread

Uncaught Exception:
Error: EIO: i/o error, lstat '/Users/athyuttamre/aeleti'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:292:14)
    at Gaze.add (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:190:8)
    at new Gaze (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/Applications/Hyper.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:86:10)
    at watch (/Applications/Hyper.app/Contents/Resources/app/config.js:42:3)
    at Object.exports.init (/Applications/Hyper.app/Contents/Resources/app/config.js:118:3)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/app/index.js:51:8)
```

Here's a [screenshot](https://www.dropbox.com/s/azmzsc7y3o0jxq3/Screenshot%202017-02-12%2015.42.03.png?dl=0). Any clue what might be wrong?

**Comment by athyuttamre** [comment]
Oh, interesting. So `/Users/athyuttamre/aeleti` is a mount point for me. I use SSHFS to mount a remote filesystem into that directory. I tried deleting and re-creating it, but then Hyper gets stuck on some of my other mount directories.

Note that I have nothing mounted right now; they just exist as empty placeholder folders for when I actually mount the remote filesystem.

**Comment by athyuttamre** [comment]
I'll correct that; I did indeed have the filesystem mounted on that folder. Either way, Hyper shouldn't crash as a result.

**Comment by rauchg** [comment]
@athyuttamre PRs welcome, a bit hard for us to test this scenario. We need to read / write to `~/.hyper.js`

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
