### ISSUE TITLE
Hyper.js stopped working on Fedora 25

### ISSUE THREAD

**Issue by possebon** [zeit/hyper#1502]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 25 - Linux 4.9.6-200.fc25.x86_64
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/possebon/d8b8625a4dc776497256686309c52a0b
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When I start the Hyper.js in Fedora 25 I'm getting this error

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: watch /home/possebon/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Gaze._watchDir (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/gaze.js:304:30)
    at /tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/gaze.js:377:10
    at iterate (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/gaze.js:373:10)
    at Gaze.add (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/gaze.js:192:8)
    at new Gaze (/tmp/.mount_PGKaAF/usr/bin/resources/app/node_modules/gaze/lib/gaze.js:74:10)
`

I can get this when I run the AppImage, when I run the installed version (suing the rpm package), I don't see any error, the Hyper.js does not appear on screen, but I have a lot of process of hyper running on background.

**Comment by ed-alertedh** [comment]
I was able to fix this in Ubuntu 16.10 by setting fs.inotify.max_user_watches in /etc/sysctl.conf as per this related issue: https://github.com/gulpjs/gulp/issues/217

Repeating the instructions here for convenience, may need to be modified to work in Fedora:
"in linux you fix this with the command:
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
