### ISSUE TITLE
Plugin load error "hyperterm-transparent-bg" failed to load in the renderer process.

### ISSUE THREAD

**Issue by leongaban** [zeit/hyper#1599]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- OSX El Capitan
- Hyper.app version: 1.2.1.1527
- [Hyperterm config gist link](https://gist.github.com/leongaban/bf7a5cd7e9edaf6f3424208aebb8ebbc)

## Issue
http://stackoverflow.com/questions/42582846/hyperterm-cannot-find-module-error-when-installing-plugins

> bundle.js:1 Error: Cannot find module '/Users/leongaban/.hyper_plugins/node_modules/hyperterm-transparent-bg' at Module._resolveFilename (module.js:455:15)

I re-installed Hyperterm and it doesn't look like it can rebuild the npm-debug.log file :(

[Here is the gist to the last npm-debug I had saved off.](https://gist.github.com/leongaban/d7a806a6bd5c984745392b33d7eccbca)

---

Update after reinstalling HyperTerm, getting material and blink plugins to work. I added `hyperterm-transparent-bg` again in the plugins, but instead of quitting and re-launching, I did View > Reload.

Then got this error:

> Uncaught Exception:
Error: Unable to parse color from string "#00000000"
    at Object.Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:34:10)
    at Color (/Applications/Hyper.app/Contents/Resources/app/node_modules/color/index.js:11:10)
    at module.exports.bgColor (/Applications/Hyper.app/Contents/Resources/app/utils/to-electron-background-color.js:7:17)
    at createWindow (/Applications/Hyper.app/Contents/Resources/app/index.js:150:24)
    at click (/Applications/Hyper.app/Contents/Resources/app/menu.js:71:11)
    at MenuItem.click (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)

![screen shot 2017-03-03 at 10 10 53 am](https://cloud.githubusercontent.com/assets/191636/23558547/b39f32d4-fff9-11e6-9e7b-316430483432.png)

**Comment by rinchen** [comment]
I had this happen myself. The problem on my end was that NPM was putting the node_modules directory under my home directory. I went into .hyper_plugins and symlinked the node_modules ala `ln -s ../node_modules ./`

**Comment by leongaban** [comment]
I got hyper-transparent to work! Apparently it's a different plugin now: https://github.com/dfrankland/hyper-transparent-bg/issues/9

**Comment by jamo** [comment]
Btw, on osx at least you can just make the background color transparent: `backgroundColor: 'rgba(37, 37, 37, 0.90)'`
