### ISSUE TITLE
Python locale features not supported

### ISSUE THREAD

**Issue by Nabellaleen** [zeit/hyper#1609]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 25 x64
- **Hyper.app version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Initial .hyper.js, without any modifications
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A (bundle.js:1 (re)loading renderer plugins // index.html:34 total init time 389.65)
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Python locale functions doesn't work ; specifically the setlocale function ( https://docs.python.org/2/library/locale.html#locale.setlocale )

This error occured during `pew` initialisation, called by my .bashrc with `source $(pew shell_config)`. Calling `pew shell_config` outside the initialisation process provoke the same error ; even just a call to `pew` have this behaviour.

`pew` is a python virtualenv manager : https://pypi.python.org/pypi/pew

For information, these errors are displayed at the terminal initialisation :
```
Traceback (most recent call last):
  File "/usr/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/lib/python2.7/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/lib/python2.7/site-packages/pew/pew.py", line 34, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/lib/python2.7/site-packages/pew/_utils.py", line 20, in <module>
    locale.setlocale(locale.LC_CTYPE, '')
  File "/usr/lib64/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Traceback (most recent call last):
  File "/usr/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/lib/python2.7/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/lib/python2.7/site-packages/pew/pew.py", line 34, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/lib/python2.7/site-packages/pew/_utils.py", line 20, in <module>
    locale.setlocale(locale.LC_CTYPE, '')
  File "/usr/lib64/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
bash: source: filename argument required
source: usage: source filename [arguments]
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (fr.UTF-8): No such file or directory
```

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
