### ISSUE TITLE
Issue packaging hyper under Arch Linux

### ISSUE THREAD

**Issue by alberto2000** [zeit/hyper#1684]
I can't  package hyper under Arch. I installed libicns, graphicsmagick, xz and rpmextract and also had to install xorriso as I was having an issue with that. But it still fails with 

> Building Snap for arch x64
> Error: spawn snapcraft ENOENT

See the complete log:

> yarn run dist
> yarn run v0.21.3
> $ npm run build && cross-env BABEL_ENV=production babel --out-file app/dist/bundle.js --no-comments --minified app/dist/bundle.js && build 
> 
> > @ build /home/thinkpad2000/Code/hyper
> > cross-env NODE_ENV=production webpack
> 
> Hash: c79ffe3902dc4c808e7c
> Version: webpack 2.2.1
> Time: 4177ms
>            Asset     Size  Chunks                    Chunk Names
>        bundle.js  1.64 MB       0  [emitted]  [big]  main
>    bundle.js.map  2.07 MB       0  [emitted]         main
> assets/icons.svg  3.34 kB          [emitted]         
>    [5] ./~/react/react.js 56 bytes {0} [built]
>    [6] ./lib/utils/plugins.js 8.82 kB {0} [built]
>   [18] ./lib/rpc.js 57 bytes {0} [built]
>   [30] ./lib/actions/sessions.js 3.16 kB {0} [built]
>   [31] ./lib/actions/term-groups.js 4.08 kB {0} [built]
>   [43] ./~/react-redux/lib/index.js 475 bytes {0} [built]
>   [72] ./lib/actions/notifications.js 347 bytes {0} [built]
>   [73] ./lib/actions/ui.js 6.28 kB {0} [built]
>   [74] ./lib/actions/updater.js 355 bytes {0} [built]
>  [130] ./lib/actions/config.js 245 bytes {0} [built]
>  [132] ./lib/containers/hyper.js 3.95 kB {0} [built]
>  [133] ./lib/store/configure-store.js 273 bytes {0} [built]
>  [134] ./lib/utils/config.js 346 bytes {0} [built]
>  [136] ./~/react-dom/index.js 63 bytes {0} [built]
>  [314] ./lib/index.js 4.06 kB {0} [built]
>     + 300 hidden modules
> Rebuilding native production dependencies for linux:x64
> Rebuilding native dependency node-pty
> ⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
> Please enable asar and use asarUnpack to unpack files that must be externally available.
> Packaging for linux x64 using electron 1.6.2 to dist/linux-unpacked
> Building AppImage for arch x64
> Building Snap for arch x64
> Error: spawn snapcraft ENOENT
>     at exports._errnoException (util.js:1033:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> From previous event:
>     at spawn (/home/thinkpad2000/Code/hyper/node_modules/electron-builder-util/src/util.ts:97:3)
>     at /home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/targets/snap.ts:123:7
>     at Generator.next (<anonymous>)
>     at /home/thinkpad2000/Code/hyper/node_modules/graceful-fs/graceful-fs.js:99:16
>     at /home/thinkpad2000/Code/hyper/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:114:15)
> From previous event:
>     at SnapTarget.build (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/targets/snap.js:155:11)
>     at postAsyncTasks.push.default.map.it (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/platformPackager.ts:103:85)
> From previous event:
>     at LinuxPackager.packageInDistributableFormat (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/platformPackager.ts:103:41)
>     at /home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/platformPackager.ts:99:10
> From previous event:
>     at LinuxPackager.pack (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/platformPackager.js:160:11)
>     at /home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/packager.ts:229:22
> From previous event:
>     at Packager.doBuild (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/packager.js:350:11)
>     at /home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/packager.ts:157:38
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:666:20)
>     at tryOnImmediate (timers.js:639:5)
>     at processImmediate [as _immediateCallback] (timers.js:611:5)
> From previous event:
>     at Packager.build (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/packager.js:256:11)
>     at /home/thinkpad2000/Code/hyper/node_modules/electron-builder/src/builder.ts:217:65
>     at Generator.next (<anonymous>)
> From previous event:
>     at build (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/builder.js:71:21)
>     at Object.<anonymous> (/home/thinkpad2000/Code/hyper/node_modules/electron-builder/out/cli/build-cli.js:71:41)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:425:7)
>     at startup (bootstrap_node.js:146:9)
>     at bootstrap_node.js:540:3
> error Command failed with exit code 255.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by stefanivic** [comment]
@alberto2000 we are familiar with the error. Snap packaging broke recently and we are in the process of fixing it. Will report back as soon as we get it fixed.

**Comment by alberto2000** [comment]
@stefanivic any news on this?
