### ISSUE TITLE
Hyper not installed

### ISSUE THREAD

**Issue by eminks** [zeit/hyper#1827]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 
- **Hyper.app version**: 1.3.3

## Issue
I tried to set up the application, but below the error screen
![screenshot_2](https://cloud.githubusercontent.com/assets/1908412/26038139/adc3e3be-3901-11e7-9c29-2527c18c945a.png)

The language of my computer is turkish

Log file=
2017-05-10 19:04:56> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-10 19:05:21> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-10 19:05:54> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-11 14:20:15> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-14 17:02:36> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-14 21:59:44> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-14 22:00:26> Unhandled exception: System.TypeInitializationException: '<Module>' tür başlatıcısı özel durum döndürdü. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 geçerli bir Win32 uygulaması değil
   --- İç özel durum yığını izlemesinin sonu ---
   konum: MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   konum: MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   konum: CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   konum: ?A0x78f04fc8.CreateCModuleInitialize()
   konum: ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   konum: _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   konum: <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- İç özel durum yığını izlemesinin sonu ---
   konum: <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   konum: .cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
2017-05-15 00:47:41> Unhandled exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x78f04fc8.CreateCModuleInitialize()
   at ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2017-05-15 01:01:57> Unhandled exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
   at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x78f04fc8.CreateCModuleInitialize()
   at ?A0x78f04fc8.??__E?A0x78f04fc8@cmiStartupRunner@@YMXXZ()
   at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

**Comment by chabou** [comment]
It seems to be related to your .NET installation: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll 

Can you try to update/reinstall it ?

**Comment by eminks** [comment]
I've reinstall but I keep getting the same error

**Comment by IvanFateev** [comment]
I'm on win 10, downloaded latest installator. I've got several errors upon installation. Hyper is installed, but fails to run with following error:
![image](https://user-images.githubusercontent.com/1488281/27119057-f0a36810-50e6-11e7-9c12-a04267fa35a4.png)

**Comment by eminks** [comment]
@IvanFateev I'm install .net framework 4.5.2 and solved the problem.

**Comment by IvanFateev** [comment]
@eminks I already have it installed

**Comment by chabou** [comment]
@IvanFateev Your issue seems not related to this one. Your installation process is ok.
Feel free to open a new issue with your specific problem with more informations (listed in issue template).

@eminks When I was asking you to update/reinstall it: 'it' was .net framework 😉 . Happy that your issue is resolved.
