### ISSUE TITLE
Checksum Mismatch: something funny going on?

### ISSUE THREAD

**Issue by martindale** [zeit/hyper#1893]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.10
- **Hyper.app version**: 216c475
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue
```
⚡ npm install
npm WARN deprecated babel-preset-es2015-node4@2.1.1: Use npmjs.org/babel-preset-env instead, see https://github.com/babel/babel-preset-env
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> electron-chromedriver@1.4.1 install /home/eric/hyper/node_modules/electron-chromedriver
> node ./download-chromedriver.js

/home/eric/hyper/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: Generated checksum for "chromedriver-v2.21-linux-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.Error (native)
    at ChecksumMismatchError.ErrorWithFilename (/home/eric/hyper/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/home/eric/hyper/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/home/eric/hyper/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:86:13)
    at Hash.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Hash.Readable.push (_stream_readable.js:134:10)
```

**Comment by Luke123443** [comment]
It's an issue of chrome-web-driver, so it' electron's fault i'd say. Try changing electron version or open an issue in the electron/electron
