### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined when installing any plugins

### ISSUE THREAD

**Issue by jonchenn** [zeit/hyper#1904]
In hyper 1.3.3, it pops up the error when I installed any plugin:

Uncaught Exception:
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.exports.onWindow (/Users/someuser/.hyper_plugins/node_modules/hyper-material-theme/index.js:8:40)
    at modules.forEach.plugin (/Applications/Hyper.app/Contents/Resources/app/plugins.js:334:14)
    at Array.forEach (native)
    at Object.exports.onWindow (/Applications/Hyper.app/Contents/Resources/app/plugins.js:332:11)
    at load (/Applications/Hyper.app/Contents/Resources/app/index.js:328:15)
    at plugins.subscribe.err (/Applications/Hyper.app/Contents/Resources/app/index.js:336:9)
    at watchers.forEach.fn (/Applications/Hyper.app/Contents/Resources/app/plugins.js:123:32)
    at Array.forEach (native)
    at err (/Applications/Hyper.app/Contents/Resources/app/plugins.js:123:18)
    at err (/Applications/Hyper.app/Contents/Resources/app/plugins.js:262:7)

E.g.
$ hpm i hyper-material-theme
hyper-material-theme installed successfully!

$ hpm -v
2.0.1

Here's my hyper version:
Version 1.3.3 (1.3.3.1754)

**Comment by chabou** [comment]
It seems to be a `hyper-material-theme` bug. 
But you said : any plugin? What is the others plugins that you tried?

**Comment by Stanzilla** [comment]
try `master` I don't think plugin stuff works in the latest release

**Comment by chabou** [comment]
@Stanzilla I tried it on `master` ;) I'm pretty sure that it is a `hyper-material-theme` issue

**Comment by Stanzilla** [comment]
@chabou derp, I'm using `hyperterm-material-theme` and it works fine, but `hyperterm-material-them` != `hyper-material-theme`

**Comment by chabou** [comment]
It works because you have a 'MaterialTheme' entry in your `.hyper.config.js` I think:
https://github.com/equinusocio/hyper-material-theme/blob/master/index.js#L8

**Comment by chabou** [comment]
@jonchenn add a 'MaterialTheme' entry in your config and feel free to open an issue in `hyper-material-theme` repo ;)

**Comment by jonchenn** [comment]
thanks for looking into this so quickly. I was misguided a ghost hyper-material-theme in my node_modules that triggers the error every time I install a plugin. Myth solved. thanks.
