### ISSUE TITLE
plugin 'Hyperline' ~ Error: Cannot find module..

### ISSUE THREAD

**Issue by RGBenderKC** [zeit/hyper#1916]
**Developer Tools details:**
bundle.js:1 Error: Cannot find module '/home/scott/.hyper_plugins/node_modules/hyperline'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/opt/Hyper/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///opt/Hyper/resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///opt/Hyper/resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///opt/Hyper/resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///opt/Hyper/resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///opt/Hyper/resources/app/dist/bundle.js:47:368728)

**Note: The "node_modules" directory does not exist.**

-

Hyper 1.3.3
Electron 1.4.16
linux x64 4.8.0-54-generic

**Comment by chabou** [comment]
What is your npm version ? We have some problems with npm@5 (fixed in master)

**Comment by RGBenderKC** [comment]
Hello!
npm version is 5.0.0.

**Comment by albinekb** [comment]
Release with a fix for this is coming 🔜

**Comment by RGBenderKC** [comment]
Great, thank you!

Update: I was able to work around the issue by creating a 'node_modules' directory; then `npm install hyperline` to it.

**Comment by Raindeer44** [comment]
Getting the same issue with other modules. Also using npm 5.0.0. I went back to 4.6.1 and it seems to work fine. I don't need npm 5.0.0 for anything else, so this is an acceptable workaround for me.

**Comment by RoyHP** [comment]
Same issue on npm 5.0.3 - This is a big deal since node 8/npm 5 are now the current stable installer.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
