### ISSUE TITLE
All plugins fail to load unless manually installed

### ISSUE THREAD

**Issue by JacobDB** [zeit/hyper#1939]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64-bit (Version 1703 OS Build 15063.413)
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/JacobDB/6ec1838fca18e61ba39a7bc7b4ab0c75
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Varies, but ocassionally get a "failed to load in the render process" error, which just says that the module doesn't exist. Example:

```bundle.js:1 Error: Cannot find module 'C:\Users\Jacob\.hyper_plugins\node_modules\hypercwd'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\Jacob\AppData\Local\hyper\app-1.3.3\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:47:368728)
    at __webpack_require__ (file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:119)
    at file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:685
    at file:///C:/Users/Jacob/AppData/Local/hyper/app-1.3.3/resources/app/dist/bundle.js:1:733
```

- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Every time I try to install any plugins, I get an error `Plugin "plugin-name" failed to load (Cannot find module 'C:\Users\Jacob\.hyper_plugins\node_modules\plugin-name').` This happens for every plugin I try installing, with a fresh install. It doesn't matter how many or which plugins I have listed in the array, i get the same error.

**Comment by abi93k** [comment]
I'm facing the same issue.

**Comment by scf4** [comment]
`cd` to `~/.hyper_plugins/`, remove `package-lock.json` and run npm i. Worked for me.

**Comment by chabou** [comment]
If you use npm@5, it duplicates #1888 😃

**Comment by JacobDB** [comment]
@chabou that's definitely it, thanks! Closing this issue, but do you know when a release will be out with the fix built in?

**Comment by niiapa** [comment]
This keeps happening to me and my friend

**Comment by chabou** [comment]
Please open a new issue with more details. We can't fix it if we can't reproduce it
