### ISSUE TITLE
Error when doing yarn run dist

### ISSUE THREAD

**Issue by dsslimshaddy** [zeit/hyper#1971]
`yarn run app` is successful but not the dist.

```
[154] ./lib/index.js 3.99 kB {0} [built]
    + 300 hidden modules
electron-builder 18.3.5
Rebuilding native production dependencies for linux:ia32
Rebuilding native dependency node-pty
Error: /usr/local/bin/node exited with code 1
Output:
make: Entering directory '/home/slim/gitRepos/branchesgits/hyper/app/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
pty.target.mk:92: recipe for target 'Release/obj.target/pty/src/unix/pty.o' failed
make: Leaving directory '/home/slim/gitRepos/branchesgits/hyper/app/node_modules/node-pty/build'

Error output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@7.9.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/slim/gitRepos/branchesgits/hyper/app/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/slim/.electron-gyp/.node-gyp/iojs-1.6.11/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/slim/.electron-gyp/.node-gyp/iojs-1.6.11',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/slim/.electron-gyp/.node-gyp/iojs-1.6.11/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/slim/gitRepos/branchesgits/hyper/app/node_modules/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from /usr/include/errno.h:28:0,
                 from /home/slim/.electron-gyp/.node-gyp/iojs-1.6.11/deps/uv/include/uv-errno.h:25,
                 from /home/slim/.electron-gyp/.node-gyp/iojs-1.6.11/deps/uv/include/uv.h:48,
                 from ../../nan/nan.h:46,
                 from ../src/unix/pty.cc:20:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-81-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/slim/gitRepos/branchesgits/hyper/app/node_modules/node-pty
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder-util/src/util.ts:135:14)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
From previous event:
    at spawn (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder-util/src/util.ts:103:3)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/yarn.ts:117:7
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/yarn.ts:115:27
From previous event:
    at rebuild (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/yarn.js:93:22)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/yarn.js:33:21)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/packager.ts:419:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/packager.js:496:11)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/packager.ts:246:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/packager.js:389:11)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/packager.ts:185:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/packager.js:284:11)
    at /home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/slim/gitRepos/branchesgits/hyper/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by waretyler** [comment]
I ran into this same issue and spent sometime figuring it out. This line gives away the issue:

`/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory`

Turns out to be an issue missing some c libraries you need to build for other architectures (32bit / 64bit). [Here's where I got that idea from](https://askubuntu.com/questions/470796/fatal-error-sys-cdefs-h-no-such-file-or-directory). You have the libraries for your system, which is why you can run the app, but had issues with the dist. To fix the issue on my system (Ubuntu) I ran ` sudo apt-get install g++-multilib`, so you would probably need to do something similar.

**Comment by albinekb** [comment]
Thanks for the info @waretyler, please re-open if this solution didnt fix it for you @dsslimshaddy
