### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by jesselcampbell** [zeit/hyper#2019]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra (10.12.5)
- **Hyper.app version**: 1.3.3.1754
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jesselcampbell/bf2101a7296558af883a4199cc397533
- **Relevant information from devtools**: `Unknown OSC code: "1"` `bundle.js:47`
- **The issue is reproducible in vanilla Hyper.app**: Have tried removing plugins and keeps happening.

## Issue

I'm getting this on a daily basis. It seems to happen intermittently. It's possible that it's more likely to happen when I'm running an npm process (as that's what I'm most frequently using Hyper for), but hard to say. A few other programs will start to error out, and then the message below will appear in a dialog from Hyper. After clicking _Okay_ on the dialog, I am forced to do a soft restart because nothing will save and programs won't open. When the computer starts back up, any programs that were previously running are in recovery mode (e.g. "Chrome didn't shut down properly...").

### Dialog Message
[Image](https://photos.app.goo.gl/45nGJyrQNMwkk0Vs1) (I had to photograph it because screen-capture couldn't write to disk after this error occurs.)

```
A Javascript error occurred in the main process
Uncaught Exception:
Error: EINVAL: invalid argument, open '/Users/jesselcampbell/Library/Application Support/Hyper/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at ElectronConfig.set store [as store] (/Applications/Hyper.app/Contents/Resources/app/node_modules/conf/index.js:90:6)
    at ElectronConfig.set (/Applications/Hyper.app/Contents/Resources/app/node_modules/conf/index.js:53:14)
    at Object.recordState (/Applications/Hyper.app/Contents/Resources/app/config.js:156:12)
    at BrowserWindow.win.on (/Applications/Hyper.app/Contents/Resources/app/index.js:356:25)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
```

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
