### ISSUE TITLE
Fail to build from source on Windows

### ISSUE THREAD

**Issue by fjsuarez** [zeit/hyper#2027]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Insider Preview Version 1703 Build 16241
- **Hyper.app version**:  Clone of master branch

## Issue
I downloaded Hyper v1.3.3 but there are several issues that are supposed to be resolved in recent commits (ctrl+, throws a js error, switch pane focus shortcut conflict just to name a few), so I decided to build Hyper from source.
It's been a bumpy road to say the least, installing `windows-build-tools` took forever, and I cannot get past `rebuild-node-pty`. It keeps throwing this error:
```
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
$ install-app-deps && npm run rebuild-node-pty
Installing app dependencies for arch x64 to C:\Users\Francisco\Documents\GitHub\Personal\hyper\app

> @ rebuild-node-pty C:\Users\Francisco\Documents\GitHub\Personal\hyper
> electron-rebuild -f -w app/node_modules/node-pty -m app

× Rebuild Failed
An unhandled error occurred inside electron-rebuild
'C:\Users\Francisco\.electron-gyp\alias.cmd' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\Francisco\.electron-gyp\alias.cmd' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16241
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Francisco\\Documents\\GitHub\\Personal\\hyper\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.11" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\Francisco\Documents\GitHub\Personal\hyper\app\node_modules\node-pty
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: 'C:\Users\Francisco\.electron-gyp\alias.cmd' is not recognized as an internal or external command,
operable program or batch file.
'C:\Users\Francisco\.electron-gyp\alias.cmd' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16241
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Francisco\\Documents\\GitHub\\Personal\\hyper\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.11" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\Francisco\Documents\GitHub\Personal\hyper\app\node_modules\node-pty
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\spawn-rx\lib\src\index.js:241:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\Users\Francisco\Documents\GitHub\Personal\hyper\node_modules\rxjs\Subscriber.js:185:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! @ rebuild-node-pty: `electron-rebuild -f -w app/node_modules/node-pty -m app`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the @ rebuild-node-pty script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francisco\AppData\Roaming\npm-cache\_logs\2017-07-26T22_55_07_892Z-debug.log
error Command failed with exit code 4294967295.
```
I'm aware this probably has to do with the tools Hyper is built upon and not a Hyper issue necessarily, but searching node-gyp and electron issues have nothing like this.

**Comment by simplex3** [comment]
Got the same problem.
