### ISSUE TITLE
Can't Install Plugins

### ISSUE THREAD

**Issue by wkyleg** [zeit/hyper#2032]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

So far I have been unable to install any themes or packages in Hyper. I just installed the latest version of Hyper on the latest version of macOS.

For this example I just limited to one plugin which I was attempting to install (hyper-wing-theme), but I have experienced the same error from other packages.

I'm assuming that Hyper just isn't able to load any packages, because when I try reinstalling with hpm, I get the error "hyper-qing-theme is already installed."

Any ideas?

**Comment by wkyleg** [comment]
Sorry forgot this:

OS: macOS 10.12.6
Hyper.app version: 1.3.3.1754
Gist: same as default with "hyper-wing-theme" in the array of plugins in hyper.js

Error Message:
bundle.js:1 Error: Cannot find module '/Users/williamkylegraves/.hyper_plugins/node_modules/hyper-qing-theme'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:368728)

As far as I know this issue should be reproducible in any vanilla hyper app as any of the plugins can't be installed. I don't think this issue is specific to any plugin I tried to install, rather Hyper itself
