### ISSUE TITLE
Hyper not launch in Deepin Linux

### ISSUE THREAD

**Issue by yofriadi** [zeit/hyper#2427]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS Deepin Linux 15.4.1
- **Hyper.app version**: 2.1.1.
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Found this installing from .AppImage
Plugin hyperborder (0.9.3) loaded.
Plugin hyperminimal (0.0.9) loaded.
running in prod mode
electron will open file:///tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/index.html
Error while loading devtools extensions TypeError: Cannot read property 'replace' of undefined
    at Object.keys.forEach.pattern (/tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/config.js:128:36)
    at Array.forEach (native)
    at Object.exports.htermConfigTranslate.config [as htermConfigTranslate] (/tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/config.js:124:32)
    at Object.exports.getDecoratedConfig (/tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/plugins.js:342:35)
    at createWindow (/tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/index.js:111:29)
    at installDevExtensions.then (/tmp/.mount_hyper-Eo9rwR/app/resources/app.asar/index.js:170:7)
    at <anonymous>
- **The issue is reproducible in vanilla Hyper.app**: I use Hyper Border & Hyper minimal

It just not doing anything after I click it or run it from albert (spotlight like app).

**Comment by ajinkyai** [comment]
I have a similar issue:




- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version (2.0.0-cancary.8)
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate



- **OS version and name**: elementary OS 0.4.1 Loki (64-bit) Built on "Ubuntu 16.04.3 LTS"
- **Hyper.app version**: 2.0.0-cancary.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ajinkyai/c8ca5f1661e6ead0e70769b1a5c6c852
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Cannot open devtools
- **The issue is reproducible in vanilla Hyper.app**: Yes (tested by removing packages from .hyper.js)

## Issue



```
~/Downloads  hyper
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Plugin hypercwd (1.1.1) loaded.
Plugin hyper-tabs-enhanced (0.4.2) loaded.
Plugin hyperterm-material (0.1.9) loaded.
Plugin hyperborder (0.9.3) loaded.
Plugin hyperlinks (0.5.0) loaded.
running in prod mode
electron will open file:///opt/Hyper/resources/app.asar/index.html
Error while loading devtools extensions TypeError: Cannot read property 'replace' of undefined
    at Object.keys.forEach.pattern (/opt/Hyper/resources/app.asar/config.js:128:36)
    at Array.forEach (native)
    at Object.exports.htermConfigTranslate.config [as htermConfigTranslate] (/opt/Hyper/resources/app.asar/config.js:124:32)
    at Object.exports.getDecoratedConfig (/opt/Hyper/resources/app.asar/plugins.js:356:35)
    at createWindow (/opt/Hyper/resources/app.asar/index.js:111:29)
    at installDevExtensions.then (/opt/Hyper/resources/app.asar/index.js:170:7)
    at <anonymous>
```
