### ISSUE TITLE
javascript error at launch

### ISSUE THREAD

**Issue by jrichard8** [zeit/hyper#2442]
- **OS version and name**: Linux DES-SI-JRI 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Hyper.app version**: 1.4.8 and 2.*
- ** I use the original hyper.js from install

I have the folowing error at start of hyper:

`Error loading config: .hyper.js:1
 [object Object]
        ^^^^^^
  SyntaxError: Unexpected identifier
    at _syntaxValidation (/opt/Hyper/resources/app.asar/config/init.js:15:12)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:28:18)
    at _import (/opt/Hyper/resources/app.asar/config/import.js:38:15)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:80:9)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:59:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:241:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
  A JavaScript error occurred in the main process
  Uncaught Exception:
  Error: watch /home/jrichard/.hyper.js ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at _watch (/opt/Hyper/resources/app.asar/config.js:34:19)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:81:3)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:59:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:241:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
  [Notification] Error loading config: SyntaxError, see DevTools for more info: undefine`

**Comment by Stanzilla** [comment]
Did you try 2.1.1 yet?

**Comment by jrichard8** [comment]
Yep I have the same error on both

**Comment by jrichard8** [comment]
Ok I found the problem: Local wasn't set correctly. the error message wasn't very explicit

**Comment by jrichard8** [comment]
finally probleme is still there

**Comment by kbrgl** [comment]
I think this is the same as #2363, I've been having the same issue.

**Comment by Stanzilla** [comment]
Please post your hyper.js file
