### ISSUE TITLE
Error message on hyper start

### ISSUE THREAD

**Issue by 7twin** [zeit/hyper#2487]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro Version 1709
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/7twin/3e6dca97b0785e62e0126b7585773518
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: No

## Issue
Each time hyper starts on my computer I get following error message:

![image](https://user-images.githubusercontent.com/32747235/33136095-a505820c-cfa4-11e7-87d6-cf120181fd65.png)

I tried executing that command on my own in cmd and get following things back in the cmd:

```
Plugin hyper-material-box (1.1.10) loaded.
Plugin hyperpower (0.2.2) loaded.
Plugin hyper-dark-scrollbar (1.1.0) loaded.
Plugin hyperborder (0.11.1) loaded.
plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file://C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\index.html
Checking for notification messages
```

after which hyper pops up and shows the error message:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\node_modules\node-pty\lib\index.js:26:12)
    at Session (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\session.js:45:18)
    at initSession (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\ui\window.js:90:23)
    at Server.Window.rpc.on.options (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\ui\window.js:93:7)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Server.ipcListener (C:\Users\X\AppData\Local\hyper\app-1.4.8\resources\app.asar\rpc.js:34:11)
    at emitTwo (events.js:106:13)

[OK]
```

This error does not happen on my laptop though, what could be the issue?

**Comment by 7twin** [comment]
This seems to happen even if I completely reinstall hyper and only change the shell to "C:\\Windows\\System32\\bash.exe".

**Comment by 7twin** [comment]
@albinekb I tried since then updating nodejs and reinstalling WSL, nothing helped, is there anything else besides resetting the entire system?

**Comment by opes** [comment]
@7twin I realize it's been some time since you posted this, but have you tried changing the shell to `wsl.exe`?

**Comment by 7twin** [comment]
@opes I have since wiped my computer and re-installed everything, it's working again, might have been an issue with node not getting cleanly uninstalled - and yes I did change it to wsl.exe
