### ISSUE TITLE
After trying to modify hyper.js, Hyper fails to launch due to a Javascript error

### ISSUE THREAD

**Issue by hThoreau** [zeit/hyper#2550]
- **OS version and name**: Subgraph Aaron 1.0 (it's based on Debian Stretch, I've installed Hyper by using its .deb file)
- **Hyper.app version**: 2.0.0-canary.8-2636
- **Link of a Gist with the contents of your .hyper.js**: https://gist.github.com/hThoreau/30cc4d9b171a6872e55badf36a4ddbb0
- **Relevant information from devtools**: Hyper fails to launch
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I've had a running version of vanilla Hyper until I've tried modifying it's hyper.js file in order to list, and have installed, some plugins. These plugins were described as such:
```
plugins: [
  'hypercwd'
  'hyper-sync-settings
  'hyperterm-paste'
],
``` 
Then I tried launching Hyper and was met with the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: watch /home/user/.hyper.js ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at _watch (/opt/Hyper/resources/app.asar/config.js:36:19)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:78:3)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:62:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:241:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
Then I've tried reinstalling it, but the error persisted. After that, I tried reinstalling after having deleted both the '.hyper.js' file and the '.hyper_plugins' folder. Same result. Downgrading to 1.4.8. Ditto.

And that's that! Thank you for your time.

**Comment by hThoreau** [comment]
Logging out and back from my user session solved this issue. It seems that Hyper must've been referring to some cache stored file.
