### ISSUE TITLE
Docker error during writing in Hyper.js

### ISSUE THREAD

**Issue by FlorianDewulf** [zeit/hyper#2595]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64 bits
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/FlorianDewulf/31aac6495e5049fc694334e25c2db53b
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, the issue happens in vanilla too

## Issue

Hi, when I use Docker with Hyper, I have an error that I didn't have few months ago. I was hoping that the issue would resolve itself with the patches done but I still have it so I create this issue.

Randomly, this error appears : 
```
Step 17/25 : RUN chmod +x $OS_BINS/cache.sh
 ---> Using cache
 Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 308, in ensure_image_exists
  File "compose\service.py", line 972, in build
  File "compose\progress_stream.py", line 23, in stream_output
  File "compose\progress_stream.py", line 90, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

It can be during the step of the Dockerfile, during the real execution of the docker tasks (like download npm modules), etc.
It's an IOError and doesn't appear when I use Git Bash, so during the output, something should not work as expected, and docker exit because it can't write.

Thanks if you can fix this, it's annoying to have a Git Bash running only for Docker commands :)

**Comment by AlexxNica** [comment]
Similar issues just for reference:
https://github.com/docker/compose/issues/5019
https://github.com/tartley/colorama/issues/101

**Comment by scottmeyer** [comment]
This may be related to this https://github.com/docker/compose/issues/5019#issuecomment-351495225

With explanation here:
https://github.com/Microsoft/vscode/issues/36630#issuecomment-350063413
