### ISSUE TITLE
Windows 10 Install error

### ISSUE THREAD

**Issue by gurpreetshanky** [zeit/hyper#2681]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1709 (16299.248) 
- **Hyper.app version**: 1.4.8 

## Issue

2018-02-17 01:35:14> Program: Starting Squirrel Updater: --install .
2018-02-17 01:35:14> Program: Starting install, writing to C:\Users\Gurpreetshanky\AppData\Local\SquirrelTemp
2018-02-17 01:35:14> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by MAPESO** [comment]
@gurpreetshanky Hi, You can reinstall it. If the problem persists, let me know 🙏

**Comment by gurpreetshanky** [comment]
@MAPESO  Thanks it working now.

**Comment by chabou** [comment]
Nice.
@gurpreetshanky, next time, please close your issue if it is resolved 😉
