### ISSUE TITLE
Hyper Froze on Emacs after C-k

### ISSUE THREAD

**Issue by dsantosp12** [zeit/hyper#2701]
- **OS version and name**: macOS High Sierra
- **Hyper.app version**: 1.4.8
- **Link of .hyper.js**: https://gist.github.com/dsantosp12/3d0447cea03c67699b869ac5eb1a793d

- **Relevant information from devtools**: Uncaught TypeError: Failed to execute 'extend' on 'Selection': parameter 1 is not of type 'Node'.
    at r.Terminal.copyStringToClipboard (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:181036)
    at r.VT.OSC.(anonymous function) (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:205660)
    at r.VT.dispatch (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:198634)
    at r.VT.parseOSC (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:202781)
    at r.VT.interpret (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:196391)
    at r.Terminal.interpret (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:47:160992)
    at r.Terminal.IO.i.hterm.Terminal.IO.writeUTF8 (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:41:17420)
    at Term.write (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:5:10530)
    at file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:18922
    at file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:18750
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When using emacs, I try C-k and Hyper froze. This is reproducible 100% of the time in my environment. 

The console logs that there is a uncaught TypeError:

<img width="839" alt="screen shot 2018-02-23 at 10 50 30 pm" src="https://user-images.githubusercontent.com/8296645/36625360-0ce07108-18ec-11e8-9a72-d15c4578e7d0.png">

**Comment by timothyis** [comment]
This should be fixed now, could you try and reproduce? 🙏

**Comment by dsantosp12** [comment]
Yep. I will try it in a bit.

**Comment by dsantosp12** [comment]
@timothyis sorry the "bit" took 29 days. I totally forgot about it. It works! Tested on my mac using Hyper 2.0.0 (stable)
