### ISSUE TITLE
Error: `node-pty` failed to load.

### ISSUE THREAD

**Issue by eujc21** [zeit/hyper#2743]
Mac 10.13.3 (17D102)
node v9.8.0
```
yarn run app
yarn run v0.21.3
$ electron app
Plugin hyper-nord (1.0.1) loaded.
App threw an error during load
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/../hyper/app/session.js:12:3)
    at Object.<anonymous> (/../hyper/app/session.js:20:9)
    at Object.<anonymous> (/../hyper/app/session.js:113:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```
https://github.com/zeit/hyper/blob/36cde0f23e27376a9ec139541f7f8b288e772999/app/session.js#L18
Possible Fix
app/session.js
```js
const nodePty = require('node-pty');
//.......
let spawn;
try {
  spawn = nodePty.spawn
} catch (err) {
  throw createNodePtyError();
}
```

**Comment by chabou** [comment]
try to clean/reinstall your dependencies: `rm -Rf node_modules && yarn`

**Comment by eujc21** [comment]
It gets stuck in a loop
```
yarn run v0.21.3
$ electron-rebuild -f -w app/node_modules/node-pty -m app
✔ Rebuild Complete
✨  Done in 2.44s.
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps && yarn run rebuild-node-pty && yarn --cwd node_modules/xterm
  • electron-builder version=19.55.2
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/edgarjoya/Documents/LocalDev/hyper/app
yarn run v0.21.3
$ electron-rebuild -f -w app/node_modules/node-pty -m app
✔ Rebuild Complete
✨  Done in 2.33s.
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps && yarn run rebuild-node-pty && yarn --cwd node_modules/xterm
  • electron-builder version=19.55.2
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/edgarjoya/Documents/LocalDev/hyper/app
yarn run v0.21.3
$ electron-rebuild -f -w app/node_modules/node-pty -m app
✔ Rebuild Complete
✨  Done in 2.43s.
```

**Comment by Lucretius** [comment]
What version of Yarn are you using?  I am on Mac OS X `v10.13.2` with Yarn `v1.3.2` and am having no issues with my build. From the output of your logs it looks like you are on an older version of Yarn?

**Comment by eujc21** [comment]
@Lucretius Yeap update brew and yarn, works.
