### ISSUE TITLE
Unable to start Hyper 1.4.8 on macOS 

### ISSUE THREAD

**Issue by Aveniir** [zeit/hyper#2814]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS High Sierra 10.13.4**: 
- **Hyper 1.4.8**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js** Not sure, where to get this, sorry :/ 
- **Relevant information from devtools** N/A 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I'm unable to run Hyper on first install. I've never used Hyper before and just downloaded it on a fresh install of Mac OS from the website. Here's the error I get:

<h3>A JavaScript error occurred in the main process</h3>

> Uncaught Exception:
ReferenceError: hyper is not defined
    at .hyper.js:118:13
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at _extract (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:6:10)
    at _init (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:30:18)
    at _import (/Applications/Hyper.app/Contents/Resources/app.asar/config/import.js:38:15)
    at Object.exports.setup (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:80:9)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:59:8)
    at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/app.asar/index.js:241:3)
    at Module._compile (module.js:571:32)

[Here's a screenshot of the error](https://i.imgur.com/tT1U2Nm.png). Any idea how to fix this?

**Comment by Aveniir** [comment]
Got it to work by downloading the latest update [here](https://github.com/zeit/hyper/releases)
