### ISSUE TITLE
Storing configuration within OneDrive is not supported

### ISSUE THREAD

**Issue by josephst** [zeit/hyper#2835]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, 64-bit (build 1709)
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/josephst/009ca506e5b1fe3f856aecb5301260b1
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

With Hyper 2.0.0 on Windows 10, storing the `.hyper.js` configuration file in OneDrive with **Files On Demand** is not supported. Attempting to run commands such as `hyper i hyper-snazzy` returns the following error:

```
Error: EINVAL: invalid argument, fstat
    at tryStatSync (fs.js:519:13)
    at Object.fs.readFileSync (fs.js:555:3)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at memoize (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:19124:15)
    at d (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:19118:22)
    at Object.exists (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:19138:10)
    at checkConfig (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:9924:11)
    at Args.args.command (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:9940:3)
    at Args.runCommand (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:11309:37)
    at Args.module.exports [as parse] (C:\Users\Joseph\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:15080:10)
```

The issue is resolved by disabling OneDrive's Files On Demand feature. The problem lies with libuv; it was fixed in [v1.14.0](https://github.com/libuv/libuv/releases/tag/v1.14.0). Node > 8.5.0 [has the fixed version of libuv](https://github.com/nodejs/node/pull/15308), but with Electron lagging behind Node, it doesn't look like this issue will be fixed until Electron 2.0 is released (looks like Node v8.9.3 will be included in that release).

For more details about the problem, see [this issue thread from Node.js](https://github.com/nodejs/node/issues/12737).

For those affected by this issue: turning off OneDrive's Files On Demand feature will fix the problem. Once Hyper starts using Electron 2.0 following its release, this issue should be fixed for good.

**Comment by chabou** [comment]
@josephst thank you so much for your detailed feedback 🙏
