### ISSUE TITLE
Not launching at all on CentOS 7 ("Javascript error occurred in the main process")

### ISSUE THREAD

**Issue by darkvertex** [zeit/hyper#2861]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: CentOS Linux release 7.4.1708 (Core)
- **Hyper.app version**: 2.0.0 I guess? I installed from the rpm `hyper-2.0.0.x86_64.rpm`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A -- it never generated one because it crashes immediately.
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue

I'm on CentOS and after installing the rpm (`hyper-2.0.0.x86_64.rpm`) as soon as I run `hyper` I am immediately greeted by an error that says:

```
A Javascript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'resize' of undefined
    at Server.Window.rpc.on (/opt/Hyper/resources/app.asar/ui/window.js:146:14)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.ipcListener (/opt/Hyper/resources/app.asar/rpc.js:33:11)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/opt/Hyper/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```
and when I press OK, the Hyper window disappears and quits.

If I run `hyper --help` from a normal terminal, it outputs the help, so it seems something broken UI-wise.

**Comment by chabou** [comment]
So issue is located here: https://github.com/zeit/hyper/blob/57c735cb6da09a109f43d39dae98beede44fa5b5/app/ui/window.js#L146

I really don't know why the session is not found. We can make a test like: https://github.com/zeit/hyper/blob/57c735cb6da09a109f43d39dae98beede44fa5b5/app/ui/window.js#L127-L133
But I'm curious to understand why it happens only in CentOS...

**Comment by wasabigeek** [comment]
@chabou I'm getting this for Ubuntu 16 too. Usually after a few restarts it works, but majorly annoying.

**Comment by JSybrandt** [comment]
This is happening on windows 10 atm.

**Comment by asrinagesh** [comment]
Also happening on OSx

**Comment by darkvertex** [comment]
I installed the canary (`hyper.x86_64 0:2.1.0_canary.2-3069`) and now the `hyper` command doesn't exist:

```
> hyper
hyper: Command not found.
```

Is this normal for canary releases? Doing `sudo repoquery -l hyper` lists nothing, as if no files had been installed. Are we positive the rpm is valid?

**Comment by darkvertex** [comment]
For my own curiosity I also tried the .AppImage file. After I chmod +x it and run it, say no to the "Do you want to integrate with system and icons?" prompt, it opens briefly and quits right away.

The terminal I ran it from doesn't hint at much...

First run:
```
 > ~/Downloads/hyper-2.1.0-canary.2-x86_64.AppImage
installed: X-AppImage-BuildId=f61a3660-418c-11a8-3bd5-8d88e2a963bd image: X-AppImage-BuildId=1c5ab680-70a2-11a8-3189-f531660e7e39
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyper-KmQJMW/app/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
```
and it quits. Then I try again:
```
> ~/Downloads/hyper-2.1.0-canary.2-x86_64.AppImage
installed: X-AppImage-BuildId=f61a3660-418c-11a8-3bd5-8d88e2a963bd image: X-AppImage-BuildId=1c5ab680-70a2-11a8-3189-f531660e7e39
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyper-3wKp6l/app/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
No matching notification messages
```
and quits again, but this time it printed one extra line, `No matching notification messages`. Not sure if that hints at anything.
