### ISSUE TITLE
Build fail 

### ISSUE THREAD

**Issue by launay12u** [zeit/hyper#2868]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MacOS 10.13.3** 
- **Hyper version 2.0**
- **Yarn version 1.6**

## Issue

I am developing a plugin, so I want to run hyper in dev mode.
So I cloned the repo but when I run `yarn` i got this error : 
```MacBook-Pro-de-Articom-Retina-3772:hyper arti-13$ yarn
yarn install v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.2.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.7.2: The platform "darwin" is incompatible with this module.
info "app-builder-bin-linux@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.7.2: The platform "darwin" is incompatible with this module.
info "app-builder-bin-win@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > electron-builder-squirrel-windows@20.5.0" has unmet peer dependency "electron-builder-lib@~20.5.0".
[4/4] 📃  Building fresh packages...
$ electron-builder install-app-deps && yarn run rebuild-node-pty && yarn --cwd node_modules/xterm
  • electron-builder version=20.5.1
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/arti-13/Projects/hyper/app
Error: /Users/arti-13/.nvm/versions/node/v9.5.0/bin/node exited with code 1
Error output:
error /Users/arti-13/Projects/hyper/app/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/arti-13/Projects/hyper/app/node_modules/node-pty
Output:
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/arti-13/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
    at ChildProcess.childProcess.once.code (/Users/arti-13/Projects/hyper/node_modules/builder-util/src/util.ts:252:14)
    at Object.onceWrapper (events.js:255:19)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:562:12)
From previous event:
    at installOrRebuild (/Users/arti-13/Projects/hyper/node_modules/electron-builder-lib/out/util/yarn.js:31:21)
    at /Users/arti-13/Projects/hyper/node_modules/electron-builder/src/cli/install-app-deps.ts:58:42
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (/Users/arti-13/Projects/hyper/node_modules/electron-builder/out/cli/install-app-deps.js:51:21)
    at then (/Users/arti-13/Projects/hyper/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (/Users/arti-13/Projects/hyper/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/arti-13/Projects/hyper/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/arti-13/Projects/hyper/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/arti-13/Projects/hyper/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/arti-13/Projects/hyper/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 
```

Please someone can help me ?

**Comment by launay12u** [comment]
Yes that was that, I re-install lastest Node and it ok

Thank for your help :+1:
