### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by david50407** [zeit/hyper#2919]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 1803 17133.1
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/david50407/f774db1511d3266a1fc7de58dba06878
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Purely just installed 1 hour ago, so yes vanilla Hyper.app 

## Issue

When calling hyper cli, it throws `Unexpected token ILLEGAL`

```
C:\Users\Davy>hyper ls

C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:29022
                throw this.createError(index, line, col, description);
                ^
Error: Line 110: Unexpected token ILLEGAL
    at ErrorHandler.constructError (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:28999:22)
    at ErrorHandler.createError (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:29015:27)
    at ErrorHandler.throwError (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:29022:21)
    at Scanner.throwUnexpectedToken (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:29150:35)
    at Scanner.scanStringLiteral (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:29924:19)
    at Scanner.lex (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:30226:26)
    at JSXParser.Parser.nextToken (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:26074:34)
    at JSXParser.Parser.parseObjectProperty (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:26557:23)
    at JSXParser.Parser.parseObjectInitializer (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:26590:35)
    at JSXParser.Parser.inheritCoverGrammar (C:\Users\Davy\AppData\Local\hyper\app-2.0.0\resources\bin\cli.js:26273:37)
```

Same result with `hyper i some-plugin`

**Comment by david50407** [comment]
Oops, I found an syntax error inside my `.hyper.js` with missing `'`. Hyper works well, sorry
