### ISSUE TITLE
notify.js exception after updating to v2.0

### ISSUE THREAD

**Issue by flekschas** [zeit/hyper#2939]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6
- **Hyper.app version**: v2.0.0
- **Plugins**:
  - hypercwd
  - hyper-material-theme
  - hyperterm-tabs

## Issue

Every now and then I am experiencing a popup with the following wonderful error message 🎉:

```
Uncaught Exception:
Error: Object has been destroyed
    at notify (/Applications/Hyper.app/Contents/Resources/app.asar/notify.js:36:8)
    at load (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:255:7)
    at Array.map (native)
    at requirePlugins (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:259:18)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:75:17)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:42:7)
    at cp.execFile.err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:27:13)
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
```

Does anybody have an idea what the source for this issue is?

The only other thing popping up in the console is:

```
Unknown OSC code: "1"
r.VT.dispatch @ bundle.js:47
Unknown OSC code: "11"
r.VT.dispatch @ bundle.js:47
```

**Comment by joeldaigle05** [comment]
Getting the same issue. Just seems to pop up every once in a while, I don't need to be running anything, just having Hyper open does the trick to reproduce.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Object has been destroyed
    at notify (/Applications/Hyper.app/Contents/Resources/app.asar/notify.js:38:8)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:105:7)
    at err (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:45:16)
    at cp.execFile (/Applications/Hyper.app/Contents/Resources/app.asar/plugins/install.js:30:15)
    at ChildProcess.exithandler (child_process.js:289:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by just-boris** [comment]
The same in 3.0. 

It regularly happens when my laptop wakes up from sleep.

https://github.com/zeit/hyper/blob/f2ecc2a7b5bec48692fe77e231b870ab7f3b3c97/app/notify.js#L38

Looking at this line I can guess that the window object is being destroyed when a laptop goes to sleep mode.

**Comment by zr2d2** [comment]
Still happens on the 3.0.2 update
