### ISSUE TITLE
Better updates system

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#30]
<img width="668" alt="screen shot 2016-07-03 at 4 29 20 pm" src="https://cloud.githubusercontent.com/assets/13041/16548190/78ec6f12-413b-11e6-8f9e-9a8586d5e7c1.png">

Goals and improvements over the ugly hack we have:
- Downloads and installs on the background, only prompts the user to restart
- Single-click restart
- Dismissable
- Green instead of red

Assets:
- Icon [icon.svg.zip](https://github.com/zeit/hyperterm/files/345353/icon.svg.zip)
- Background color: #7ED321
- Dismiss link color: #528D11

Thanks to @matiastucci for bringing [this electron API](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) to my attention.

**Comment by rauchg** [comment]
This might also require updates to [hyperterm-website](https://github.com/zeit/hyperterm-website).

**Comment by numeraltwo** [comment]
@rauchg looking at this tonight.

**Comment by rauchg** [comment]
@numeraltwo excellent!

**Comment by matiastucci** [comment]
hey @numeraltwo, I deployed a server here https://nuts-serve-nxchetcjig.now.sh/update/osx/${CURRENT_VERSION} to check if there is an update or not. It's using GitHub releases to check that.

I started this the other day but the `autoUpdater` events didn't fire. For example: `autoUpdater.once('checking-for-update', () => { /.../ });` I don't know why. Maybe you'll have more luck. When I have more free time I'll try again

**Comment by rauchg** [comment]
@matiastucci awesome! I'll set up a Slack in case you guys want to work together on this one

**Comment by matiastucci** [comment]
Ok, sure @rauchg. That would be great.

**Comment by matiastucci** [comment]
Ok, this morning I spend some time on this. Here is my fork: https://github.com/matiastucci/hyperterm

I wrote a quick `autoUpdater` module, and is detecting when there is a new update. But after downloading it Squirrel is throwing this error: `Code signature at URL file:///Users/Mati/Library/Caches/co.zeit.hyperterm.ShipIt/update.zH0J7it/HyperTerm.app/ did not pass validation: code failed to satisfy specified code requirement(s)`

I'm pretty sure that error is because I'm signing the app with my User ID. I think the only way to test this is signing the app the same way as the releases. Any ideas?

**Comment by matiastucci** [comment]
Ok, is definitely that. Before I was signing the app with my identity and getting the update from GitHub releases (signed it with some other identity). Now, I signed 2 versions (3.0.1 and 3.0.2) both with **my** identity. I uploaded the 3.0.2 to the server, ran the 3.0.1 and now it works.

![ezgif-2544192603](https://cloud.githubusercontent.com/assets/3856355/16640572/58330d7e-43f9-11e6-9726-7b2b44a84ad9.gif)

A couple of things:
1. If you run `npm start` is going to throw an error saying that the app is not signed. This is because I'm importing `autoUpdater` and Squirrel requires the app to be signed. So, to test it I'm doing `./package.sh` everytime. Of course this sucks, and it has to be some way to sign the running app but I don't know how yet.
2. For this to actually work with GitHub releases the app is going to need to be signed with the same identity.
3. I'm not sure how to fix this without pushing the identity to GitHub 🤔

**Comment by rauchg** [comment]
@matiastucci amazing

**Comment by leo** [comment]
Something like this would be great as well:

<img src="https://cloud.githubusercontent.com/assets/6170607/16837296/ba1b4a8c-49c2-11e6-97b2-216e0d76038d.png" width="400">

**Comment by Stanzilla** [comment]
Btw, the current update server is not working:

```
2017-01-11 07:55:10> FileDownloader: Downloading url: https://hyper-updates.now.sh/update/win32/1.0.1/releases?id=hyper&localversion=1.0.1&arch=amd64
2017-01-11 07:55:11> IEnableLogger: Failed to download url: https://hyper-updates.now.sh/update/win32/1.0.1/releases?id=hyper&localversion=1.0.1&arch=amd64: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2017-01-11 07:55:11> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-01-11 07:55:11> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---


```

**Comment by curz46** [comment]
This issue can be closed as it has been implemented.

**Comment by albinekb** [comment]
Closing 👌
