### ISSUE TITLE
No info about how to install plugins, themes and etc on both official website and github

### ISSUE THREAD

**Issue by gerchicov-bp** [zeit/hyper#3100]

**Comment by thedch** [comment]
@timothyis the `install` button gives the (rather short) prompt:

>Use the hyper command, bundled with your Hyper app, to install hyper-opacity by entering the following into Hyper:

`hyper i hyper-opacity`

***

I wouldn't complain about the prompt being short, but there's no hyper command bundled with the app. I have no idea what that's referring to. There's no further documentation on this `hyper` command, and I have no idea how to install it. 

On my system (Windows 10, Bash for Windows):

```
$ hyper --help
HyperRogue by Zeno Rogue <zeno@attnam.com>, version 4.2released under GNU General Public License version 2 and thus
comes with absolutely no warranty; see COPYING for details
Press F1 while playing to get ingame options.

HyperRogue accepts the following command line options:
  -c FILE        - use the specified configuration file
  -s FILE        - use the specified highscore file
  -m FILE        - use the specified soundtrack (music)
  --version, -v  - show the version number
  --help, -h     - show the commandline options
  -f, -w         - start in the fullscreen or windowed mode
  -e, -a, -p     - start in the Escher, ASCII, or Plain mode
  -r WxHxF       - use the given resolution and font size
  -o             - switch the OpenGL mode on or off
```

It seems that my `hyper` command is very different from the `hyper` command that the website references. Thus, I have no idea how to install any of the plugins or themes. Any help is appreciated, if you're able to point me in the right direction I'd be happy to make some additions to the README for future confused users.

**Comment by timothyis** [comment]
Oh, very interesting @thedch. I think we should create some more documentation and link it in this case 🙏

**Comment by thedch** [comment]
@timothyis -- sounds good to me, can I help?

**Comment by albinekb** [comment]
Here's the code that installs the CLI on win32: https://github.com/zeit/hyper/blob/canary/app/utils/cli-install.js#L91-L102

I think it won't overwrite your current `hyper` command because of [this](https://github.com/zeit/hyper/blob/canary/app/utils/cli-install.js#L60)

**Comment by gerchicov-bp** [comment]
@timothyis 
`The goal of the project is to create a beautiful and extensible experience for command-line interface users...`
very "beautiful" and "UI-UX friendly"? I found install button when you mentioned it only

**Comment by thedch** [comment]
@albinekb That link is to the canary branch... does https://hyper.is/#installation pull from canary?

**Comment by timtorres** [comment]
I have the same problem after installing vanilla 64bit Hyper on Win10. Instructions say 'hyper' command is bundled with the install, but I get ```
'hyper' is not recognized as an internal or external command,
operable program or batch file.
```
Hyper's bin path was added to my user Path variable but...
wait, I took the value from the user Path and added it to the system Path and it worked! @thedch could you try this?

**Comment by gwiedeman** [comment]
I also find the docs unclear for Windows, and I'm confused how to set up plugins on windows using the bash shell. I think this is also an issue with the general bash on windows setup and what's installed on which.

I also installed Hyper 2.0.0 with the default 64-bit installer, without node or npm. It appears that some plugins install just by adding them to the .hyper (this worked for hyper-material-theme) but others require npm or the hyper command... right?... maybe?

Neither hypercwd or hyper-blink seem to work.

I have no hyper command by default, as `which hyper` returns nothing. Adding the Hyper to my windows path provides the command to Powershell, but not Bash. Adding the same windows Path to Hyper in %AppData% to .bashrc to $Path correctly (I think?) still doesn't add the command to which hyper.

Running `hyper` from Powershell then returns this:

```
Opening 
Plugin hyper-material-theme (2.0.6) loaded.
Plugin hyper-blink (1.1.2) loaded.
running in prod mode
electron will open file://C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\index.html
Failed to add Hyper CLI path to user PATH { Error: spawn EPERM
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:505:9)
    at Registry.values (C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\node_modules\winreg\lib\registry.js:443:14)
    at Promise (C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\utils\cli-install.js:53:12)
    at Promise (<anonymous>)
    at exports.addBinToUserPath (C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\utils\cli-install.js:51:10)
    at Object.<anonymous> (C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\index.js:103:5)
    at Object.<anonymous> (C:\Users\[ME]\AppData\Local\hyper\app-2.0.0\resources\app.asar\index.js:279:3)
    at Module._compile (module.js:569:30) code: 'EPERM', errno: 'EPERM', syscall: 'spawn' }
Checking for notification messages
No matching notification messages
```

I installed node and npm after in Bash, but the `npm install hypercwd` runs but has no effect on the shell.

I installed hyper in bash with npm and that also ran, but had no effect.

**Comment by tomasdev** [comment]
```
tomasroggero@tomasroggero-imacpro in ~
$ hyper i hyper-material-theme
/Users/tomasroggero/Applications/Terminal.app/Contents/Resources/bin/cli.js:19156
      getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
                                                                              ^

TypeError: Cannot read property 'right' of undefined
```

For me... the site now has _some_ docs https://hyper.is/plugins/hyper-material-theme but most things don't seem to work
