### ISSUE TITLE
Can't open Hyper after change Shell into Powershell.

### ISSUE THREAD

**Issue by fuaditrockz** [zeit/hyper#3177]
When I changed my 'Preferences' shell to 'PowerShell' like this 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'. Then, I started again my Hyper. Voillaaa... my Hyper Apps was force closed/cannot open again and again. When I test find to Troubleshooter, I've find this;
'A Javascript Error Occured in the main process
Uncaught exception:
Error: connect ENOENT
\\.\pipe\winpty-conin-12540-1-1d[very long number]
at Object.exports_errnoException(util.js:1024:11)
at exports_exceptionWithHostPort(util.js:1047:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)'

I've uninstall and install it again, but I find same error everytime. I've used Windows 10 btw. Thanks for help before...

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** win32 x64 6.2.9200
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by Mat-thieu** [comment]
@fuaditrockz So you didn't manage to get powershell to work with hyper? Mine keeps crashing.

**Comment by caryleo** [comment]
I've solved this: 
Just below the SHELL entry, there is a SHELLARGS entry. I delete the '--login' string and it works, which is already mentioned in the comments :)

**Comment by Denzic** [comment]
> I have the same issue but i got 2 errors. I'm running on v2.1.2
> 
> Errors:
> 'A Javascript Error Occured in the main process
> Uncaught exception:
> Error: connect ENOENT
> .\pipe\winpty-conin-12540-1-1d[very long number]
> at Object.exports_errnoException(util.js:1024:11)
> at exports_exceptionWithHostPort(util.js:1047:20)
> at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)'
> 
> 'A Javascript Error Occured in the main process
> Uncaught exception:
> Error: connect ENOENT
> .\pipe\winpty-conout-4892-1-1d[very long number]
> at Object.exports_errnoException(util.js:1024:11)
> at exports_exceptionWithHostPort(util.js:1047:20)
> at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)'
> 
> I tried reinstalling and resetting the hyper.js file by removing it, I STILL get the same error.
> But when I run the installer, it runs smooth, the error will only show when I reopen hyper.
> 
> Am I missing something here?

I have the exact same problem here.
