### ISSUE TITLE
Hyper 2.1.0 doesn't open Ubuntu 18.04

### ISSUE THREAD

**Issue by raghav-kukreti** [zeit/hyper#3221]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04
- **Hyper.app version**: 2.1.0

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**: True

## Issue

I have a fresh Ubuntu 18.04 install. I installed hyper v2.1.0 from the releases page.

On running `hyper -v` I get,

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/raghavkukreti/.config/Hyper/config.json.3982131248'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Function.writeFileSync [as sync] (/opt/Hyper/resources/app.asar/node_modules/write-file-atomic/index.js:180:17)
    at ElectronConfig.set store [as store] (/opt/Hyper/resources/app.asar/node_modules/conf/index.js:94:19)
    at ElectronConfig.Conf (/opt/Hyper/resources/app.asar/node_modules/conf/index.js:38:14)
    at ElectronConfig (/opt/Hyper/resources/app.asar/node_modules/electron-config/index.js:11:3)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/config/windows.js:9:13)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/config/windows.js:24:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

[3558:0923/060556.952017:ERROR:cache_util.cc(134)] Unable to move cache folder /home/raghavkukreti/.config/Hyper/GPUCache to /home/raghavkukreti/.config/Hyper/old_GPUCache_000
[3558:0923/060556.952054:ERROR:disk_cache.cc(132)] Unable to create cache
[3558:0923/060556.952058:ERROR:shader_disk_cache.cc(604)] Shader Cache Creation failed: -2
```

**Comment by raghav-kukreti** [comment]
A small update on this. I chown'd the .config folder and Hyper started opening.
Is this a problem during installation?

Some NPM permissions?
