### ISSUE TITLE
Error: Error launching WinPTY agent

### ISSUE THREAD

**Issue by plutoid** [zeit/hyper#3505]
- [ ] Your Hyper.app version is **2.1.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at new WindowsPtyAgent (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\node_modules\node-pty\lib\index.js:27:12)
    at Session (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\session.js:53:18)
    at initSession (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\ui\window.js:102:24)
    at Server.Window.rpc.on.options (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\ui\window.js:105:7)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.ipcListener (C:\Users\c5197505\AppData\Local\hyper\app-2.1.2\resources\app.asar\rpc.js:33:11)
    at emitTwo (events.js:125:13)

[OK]

 - **Hyper version**: undefined "2.1.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by plutoid** [comment]
copy binary WIN-pty and solved this, due to this is known issue.
