### ISSUE TITLE
Error launching 'hyper list' on macos

### ISSUE THREAD

**Issue by jchomarat** [zeit/hyper#3531]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macos 10.14.2
- **Hyper.app version**: 2.1.2

## Issue
Hello team,

I have a fresh install of Hyper, from brew, and when I launch the command 'hyper i *theme*' or 'hyper list' to see installed plugin, I receive the following error:

/Applications/Hyper.app/Contents/Resources/bin/cli.js:26006
	        throw this.unexpectedTokenError(token, message);
	        ^
Error: Line 15: Unexpected token ,
    at ErrorHandler.constructError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29015:22)
    at ErrorHandler.createError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:29031:27)
    at JSXParser.Parser.unexpectedTokenError (/Applications/Hyper.app/Contents/Resources/bin/cli.js:25996:39)
    at JSXParser.Parser.throwUnexpectedToken (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26006:21)
    at JSXParser.Parser.parseObjectProperty (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26595:23)
    at JSXParser.Parser.parseObjectInitializer (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26606:35)
    at JSXParser.Parser.inheritCoverGrammar (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26289:37)
    at JSXParser.Parser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26358:38)
    at JSXParser.parsePrimaryExpression (/Applications/Hyper.app/Contents/Resources/bin/cli.js:24477:97)
    at JSXParser.Parser.inheritCoverGrammar (/Applications/Hyper.app/Contents/Resources/bin/cli.js:26289:37)
~:

Any idea?
Thanks a lot
- Julien

**Comment by jchomarat** [comment]
My bad ... wrong configuration file
Great work guys

**Comment by famasoon** [comment]
Hi @jchomarat ,
How to fix this issue?
I am also in trouble with the same problem ...

**Comment by jchomarat** [comment]
Hello @famasoon - as I said after, it was a json formatting error of my configuration file. Check it, and see if it solves the issue

**Comment by famasoon** [comment]
Sorry, I checked `.hyper.js`, and I found formatting error in `fontFamily` settings. I modified it, Hyper works well.
Thanks @jchomarat  :bow:

**Comment by alecbz** [comment]
I think a clearer error message is still warranted as a fix here? Nothing in the error message points to `~/.hyper.js`.
