### ISSUE TITLE
Reopening hyper after installation throws an error

### ISSUE THREAD

**Issue by techuila** [zeit/hyper#3565]
I tried reinstalling and resetting the hyper.js file by removing it, also tried removing remaining contents on registry. I STILL get the same error.
But when I run the installer, it runs smooth, the error will only show everytime I reopen hyper after installation.

What am I missing something here?

Errors:
'A Javascript Error Occured in the main process
Uncaught exception:
Error: connect ENOENT
.\pipe\winpty-conin-12540-1-1d[very long number]
at Object.exports_errnoException(util.js:1024:11)
at exports_exceptionWithHostPort(util.js:1047:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)'

'A Javascript Error Occured in the main process
Uncaught exception:
Error: connect ENOENT
.\pipe\winpty-conout-4892-1-1d[very long number]
at Object.exports_errnoException(util.js:1024:11)
at exports_exceptionWithHostPort(util.js:1047:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)'

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by timothyshores** [comment]
<img width="417" alt="Screen Shot 2019-05-16 at 10 48 44 PM" src="https://user-images.githubusercontent.com/8406571/57902514-1acdc600-782f-11e9-9549-01e90c2d77bc.png">

I'm having a similiar issue with Hyper 3.0.2 on OSX 10.14.1
