### ISSUE TITLE
Unknown encoding: cp0

### ISSUE THREAD

**Issue by Mossop** [zeit/hyper#3606]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1809
- **Hyper.app version**: 3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Mossop/b1856e5a9c4a12bd5e423fbca1279fcf
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I just upgraded to Hyper 3, fixed the configuration that it lost and then tried using it. Immediately I found that a python script I need for my work fails to run with an unknown encoding error:

```
Traceback (most recent call last):
  File "mach", line 86, in <module>
    main(sys.argv[1:])
  File "mach", line 82, in main
    sys.exit(mach.run(args))
  File "c:\mozilla\source\trunk\python/mach\mach\main.py", line 369, in run
    self._print_error_header(argv, sys.stdout)
  File "c:\mozilla\source\trunk\python/mach\mach\main.py", line 581, in _print_error_header
    fh.write('Error running mach:\n\n')
LookupError: unknown encoding: cp0
 ```

This is a python script running under an msys bash.

**Comment by WestedCrean** [comment]
I have this issue too, basically it prevents me from using hyper productively on Windows 10

- OS version and name: Windows 10 1809
- Hyper.app version: 3.0.0
- Link of a Gist with the contents of your .hyper.js: 
https://gist.github.com/WestedCrean/26b9155be4bec2246389f5d1928b232d
- Relevant information from devtools (CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere): none
- The issue is reproducible in vanilla Hyper.app: yes

**Comment by vannaka** [comment]
Hey guys. I found a workaround for this problem. https://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash?answertab=active#tab-top
