### ISSUE TITLE
Error: Missing required channel argument

### ISSUE THREAD

**Issue by niedzielski** [zeit/hyper#371]
I'm on Ubuntu v16.04.1 which I know isn't officially supported yet but it sounded like other folks were running ok more or less. On 0782c77, `./scripts/install.sh && npm i && npm start` launches the app but immediately pops open a dialog with the following error:

```
Uncaught Exception:
Error: Missing required channel argument
    at sendWrapper (/home/stephen/opt/hyperterm/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/web-contents.js:105:13)
    at Server.emit (/home/stephen/opt/hyperterm/rpc.js:35:13)
    at BrowserWindow.rpc.win.on (/home/stephen/opt/hyperterm/index.js:169:11)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)
```

The screen is blank and unfortunately unusable. Maybe I'm just doing something wrong?

**Comment by rauchg** [comment]
:O sounds like an Electron bug somehow?

**Comment by ekmartin** [comment]
Pretty sure this has been resolved since this. Let me know if it still persists and I'll reopen.
