### ISSUE TITLE
TermGroup crashes often

### ISSUE THREAD

**Issue by dominikzogg** [zeit/hyper#3790]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 19.04
- **Hyper.app version**: 3.0.2
- **.hyper.js**: [Gist](https://gist.github.com/dominikzogg/5dff1d451da360e576acfbf5e9970f8f)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: ```
bundle.js:1 DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Term.componentDidMount (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:369311)
    at commitLifeCycles (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:237943)
    at b (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:241550)
    at m (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:247071)
    at w (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:246821)
    at z (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:245926)
    at u (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:245315)
    at Object.enqueueSetState (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:219283)
    at Connect.A.setState (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:184136)
    at Connect.onStateChange (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:98837)
bundle.js:1 [Notification] Plugin error: Plugins decorating Term has been disabled because of a plugin crash. Check Developer Tools for details.```
- **The issue is reproducible in vanilla Hyper.app**: There is no addon installed

## Issue
This happens when creating new term group or removing it.

**Comment by Stanzilla** [comment]
Try again with a recent canary CI build please

**Comment by dominikzogg** [comment]
@Stanzilla you mean following the build instructions here: https://github.com/zeit/hyper#contribute ?

**Comment by Stanzilla** [comment]
Oh I did not notice that our Linux travis builds don't provide artifacts, yeah you would have to build it yourself then, sorry

**Comment by dominikzogg** [comment]
@Stanzilla its not fixed within canary

**Comment by dominikzogg** [comment]
seems to work better but the TermGroup crashed ones.

```
sudo apt install graphicsmagick icnsutils xz-utils
git clone git@github.com:zeit/hyper.git
yarn
yarn run dev
yarn run app => in another terminal
```

**Comment by bet4it** [comment]
Duplicate of #3749

**Comment by dominikzogg** [comment]
ah that's the reason, yeah i use this char often

**Comment by ken0x0a** [comment]
@Stanzilla Could you give me how to use "canary CI build" please?
I changed config "updateChannel" => "canary" but hyper.app was not updated to 3.1.0-canary.1
