### ISSUE TITLE
Cannot find module 'native-reg' on Linux

### ISSUE THREAD

**Issue by bet4it** [zeit/hyper#4320]
- **OS version and name**: Arch Linux
- **Hyper.app version**: 3.1.0-canary.4

## Issue

```
❯ ./Hyper-3.1.0-canary.4.AppImage
Error: Cannot find module 'native-reg'
Require stack:
- /tmp/.mount_Hyper-Rmq6V0/resources/app.asar/utils/cli-install.js
- /tmp/.mount_Hyper-Rmq6V0/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7646:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function._load (/tmp/.mount_Hyper-Rmq6V0/resources/app.asar/plugins.js:82:37)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/tmp/.mount_Hyper-Rmq6V0/resources/app.asar/utils/cli-install.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:880:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Hyper-Rmq6V0/resources/app.asar/utils/cli-install.js',
    '/tmp/.mount_Hyper-Rmq6V0/resources/app.asar/index.js',
    undefined
  ]
}
```

**Comment by bet4it** [comment]
@LabhanshAgrawal

**Comment by LabhanshAgrawal** [comment]
Native-reg's just there for windows, this message is from the try catch block while importing it. Shouldn't affect anything, can remove the console log from catch block if desired.

**Comment by bet4it** [comment]
Why not check `process.platform` before import?
