### ISSUE TITLE
Uncaught Exception when opening preferences

### ISSUE THREAD

**Issue by joakin** [zeit/hyper#495]
It's happened a few times today, I'm not sure of how to reproduce it though. With a couple of tabs open doing work, I'll ⌘<comma> to go to .hyperterm.js and this trace pops up in an alert:

```
Uncaught Exception:
Error: This socket is closed
    at PtyRwStream.Socket._writeGeneric (net.js:672:19)
    at PtyRwStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at PtyRwStream.Writable.write (_stream_writable.js:220:11)
    at PtyRwStream.Socket.write (net.js:650:40)
    at Session.write (/Applications/HyperTerm.app/Contents/Resources/app/session.js:104:20)
    at Server.rpc.on (/Applications/HyperTerm.app/Contents/Resources/app/index.js:162:25)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
```

Tab stays blank and unresponsive after that. Some times it happens from there onwards trying to open new tabs, sometimes it doesn't. Restarting the app fixes it.
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 15.5.0

**Comment by db2k** [comment]
@leo 

Happens also on Linux
`session.get(uid)` returns `undefined`

**Comment by ekmartin** [comment]
Can you still reproduce this in the latest release (0.8.*)?

**Comment by joakin** [comment]
From what I've been using it (a couple of hours) I haven't found the issue again. Maybe @db2k can check on linux.

**Comment by flybayer** [comment]
I think this can be closed.
