### ISSUE TITLE
Exception on new window

### ISSUE THREAD

**Issue by davidhariri** [zeit/hyper#676]
When I make a new window in HyperTerm 0.7.1 (0.7.1.36) I get this:

```
Uncaught Exception:
Error: spawn /usr/local/bin/zsh ENOENT
    at Object.exports._errnoException (util.js:949:11)
    at Socket.<anonymous> (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/child_pty/lib/child_pty.js:103:15)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
```

**Comment by flybayer** [comment]
@davidhariri, is this using the precompiled Linux binary or a binary you built yourself?

**Comment by matheuss** [comment]
@flybayer I think he's on macOS :P

**Comment by jbergstroem** [comment]
Did you remove `zsh` from homebrew or something?

**Comment by flybayer** [comment]
I think this can probably be closed
