### ISSUE TITLE
Fails to run on Raspberry Pi OS arm64

### ISSUE THREAD

**Issue by balupton** [zeit/hyper#7794]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `Linux raspberrypi 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux`
- **Hyper.app version**: `3.4.1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: just installed, no config

## Issue

Installed via https://releases.hyper.is/download/deb_arm64 on a fresh Raspberry Pi OS arm64 on a Raspberry Pi 400

```
> hyper --verbose
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Hyper/resources/app.asar/session.js
- /opt/Hyper/resources/app.asar/ui/window.js
- /opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Hyper/resources/app.asar/session.js',
    '/opt/Hyper/resources/app.asar/ui/window.js',
    '/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}

A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

[24869:0215/102228.702961:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[24869:0215/102228.703102:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.

The futex facility returned an unexpected error code.
```

This issue seems related https://github.com/vercel/hyper/issues/6937 however was already fixed in 2022

**Comment by curiosity654** [comment]
Same problem on Jetson Orin here, but the 2022 artifacts are expired now.

**Comment by dvelaren** [comment]
Same problem on Raspberry Pi 5 (Raspberry Pi OS 64 bits) latest version
