### ISSUE TITLE
`node-pty` failed to load NIXOS

### ISSUE THREAD

**Issue by gopmur** [zeit/hyper#7945]
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js
- /nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js
- /nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js',
    '/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/ui/window.js',
    '/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/nix/store/zvhz3g3j66643gc8pz6m82c4fs8p94g5-hyper-3.4.1/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

Installed it using configuration.nix in nixos.
hyper does not open.

**Comment by oenu** [comment]
Same install, same issue

**Comment by midischwarz12** [comment]
Yes, same issue. It looks like the `node-pty` package is missing in the `package.json`, so that might be why it is failing. This is the relevant [issue on nixpkgs](https://github.com/NixOS/nixpkgs/issues/261209)
