### ISSUE TITLE
Unable to launch on Ubuntu 24.04 intel

### ISSUE THREAD

**Issue by impeterk** [zeit/hyper#7996]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 24.04
- **Hyper.app version**: 3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes 

## Issue

I have installed hyper on freshly installed ubuntu 24.04 but I was not able to launch it. 
I have tried 
 - official .deb package
 - official .snap package
 - pacstall package
 - official .Appimage

All version displayed this message

``` bash
~:$ hyper -v
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
    at _extract (/opt/Hyper/resources/app.asar/config/init.js:14:15)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:35:28)
    at _import (/opt/Hyper/resources/app.asar/config/import.js:113:37)
    at Object.setup (/opt/Hyper/resources/app.asar/config.js:99:32)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:50:8)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)

[29128:0628/231441.643707:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

[29161:0628/231441.769708:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

#### Report details
- **Date generated:**                              2024-06-28 23:35:21

#### Hardware Information:
- **Hardware Model:**                              Lenovo ThinkBook 14 G6 IRL
- **Memory:**                                      16,0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i7-13700H × 20
- **Graphics:**                                    Intel® Graphics (RPL-P)
- **Disk Capacity:**                               1,0 TB

#### Software Information:
- **OS Name:**                                     Ubuntu 24.04 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-36-generic

**Comment by MissingSignal** [comment]
Hyper is not yet supported on Ubuntu 24.04

As stated [here](https://github.com/vercel/hyper/issues/7915#issuecomment-2113323480) a workaround is: 
```
sudo chmod 4755 /opt/Hyper/chrome-sandbox
```
after the installation of the .deb file

**Comment by impeterk** [comment]
> Hyper is not yet supported on Ubuntu 24.04
> 
> As stated [here](https://github.com/vercel/hyper/issues/7915#issuecomment-2113323480) a workaround is:
> 
> ```
> sudo chmod 4755 /opt/Hyper/chrome-sandbox
> ```
> 
> after the installation of the .deb file

Funny 
I have tried that first time around, did not work. 
reinstalled hyper and it seems to work... Lovely

**Comment by add-n2x** [comment]
Re-installed hyper, applied the workaround and still doesn't work

```bash
hyper -v
[7402:0715/112519.282152:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)
```

**edit**: but this worked -

```bash
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```
