### ISSUE TITLE
dev: `yarn run dev` errors with stock Python 3.12

### ISSUE THREAD

**Issue by corneliusroemer** [zeit/hyper#8027]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

I've cloned the canary branch (default).

- **OS version and name**: Darwin m2-mini 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64
- **Hyper.app version**: canary

## Issue

I'm trying to get hyper working locally using dev setup. I followed the README.md:

- Install yarn (`v1.22.22`)
- Run `yarn`
- Run `yarn run dev`

However I get an error:

```
$ yarn run dev
$ electron-rebuild -f -o node-pty -m target
⠴ Building module: node-pty, Completed: 0Traceback (most recent call last):
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/Users/corneliusroemer/code/hyper/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/corneliusroemer/code/hyper/target/node_modules/node-pty'

Error: node-gyp failed to rebuild '/Users/corneliusroemer/code/hyper/target/node_modules/node-pty'
    at ChildProcess.<anonymous> (/Users/corneliusroemer/code/hyper/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It looks like the README is not up to date regarding dev setup on macos.

**Comment by corneliusroemer** [comment]
I tried running `yarn install` but that errored (now with yarn v4):

```
yarn install
➤ YN0000: · Yarn 4.4.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @ava/babel@npm:2.0.0, @ava/typescript@npm:4.1.0, @babel/cli@npm:7.24.1, @babel/core@npm:7.24.4, and 1244 more.
➤ YN0000: └ Completed in 3s 711ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1248 packages were added to the project (+ 621.8 MiB).
➤ YN0000: └ Completed in 5s 927ms
➤ YN0000: ┌ Link step
➤ YN0007: │ electron-mksnapshot@npm:29.3.0 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:22.3.25 must be built because it never has been before or the last one failed
➤ YN0007: │ leveldown@npm:5.6.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ hyper@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ hyper@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/4_/fz5f9npd7wg7d8fqn1c9n3yh0000gn/T/xfs-ab7b950e/build.log)
➤ YN0000: └ Completed in 29s 632ms
➤ YN0000: · Failed with errors in 39s 356ms
```

**Comment by corneliusroemer** [comment]
I got further by:
- Pinning node to v20 (instead of latest)
- Using classic yarn

But thing still error our:

```
yarn run v1.22.22
$ electron-rebuild -f -o node-pty -m target
⠴ Building module: node-pty, Completed: 0Traceback (most recent call last):
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/corneliusroemer/code/hyper/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/Users/corneliusroemer/code/hyper/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/corneliusroemer/code/hyper/target/node_modules/node-pty'

Error: node-gyp failed to rebuild '/Users/corneliusroemer/code/hyper/target/node_modules/node-pty'
    at ChildProcess.<anonymous> (/Users/corneliusroemer/code/hyper/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by corneliusroemer** [comment]
Current `electron-rebuild` is not compatible with Python 3.12, see https://github.com/electron/rebuild/issues/1116

You can fix by installing setuptools manually in your Python installation.

```
pip install setuptools
```
