### ISSUE TITLE
Closing a tab results in a blank screen

### ISSUE THREAD

**Issue by philip-peterson** [zeit/hyper#8032]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS 14.4.1 Sonoma
- **Hyper.app version**: 2a7bb18259d975f27b30b502af1be7576f6f5656
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

```
<embedded>:23937 Uncaught TypeError: Cannot read properties of undefined (reading 'onRequestRedraw')
    at t.RenderService.setRenderer (<embedded>:23937:107471)
    at Object.dispose (<embedded>:23933:91675)
    at a.dispose (<embedded>:23933:74208)
    at t.AddonManager._wrappedAddonDispose (<embedded>:23937:253461)
    at t.dispose (<embedded>:23937:253188)
    at t.AddonManager.dispose (<embedded>:23937:253070)
    at d.dispose (<embedded>:23937:190098)
    at d.dispose (<embedded>:23937:282496)
    at Terms.componentDidUpdate (terms.tsx:65:1)
    at commitLayoutEffectOnFiber (<embedded>:50695:36)

The above error occurred in the <Terms> component:

    at Terms (file:///Users/ironmagma/Code/hyper/target/renderer/bundle.js:4796:5)
    at DecoratedComponent (file:///Users/ironmagma/Code/hyper/target/renderer/bundle.js:2254:7)
    at ConnectFunction (<embedded>:57692:80)
    at forwardConnectRef
    at div
    at div
    at file:///Users/ironmagma/Code/hyper/target/renderer/bundle.js:1410:66
    at DecoratedComponent (file:///Users/ironmagma/Code/hyper/target/renderer/bundle.js:2192:7)
    at DecoratedComponent (file:///Users/ironmagma/Code/hyper/target/renderer/bundle.js:2254:7)
    at ConnectFunction (<embedded>:57692:80)
    at forwardConnectRef
    at Provider (<embedded>:63116:9)

React will try to recreate this component tree from scratch using the error boundary you provided, DecoratedComponent.
```

- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Closing a tab with CMD-W (or Shell > Close) results in a blank screen. This occurs on `canary` but not `v4.0.0-canary.5`.

**Comment by philip-peterson** [comment]
This appears to be new since 632a110effeb2d236a76ec83fb232b1f0d7c9531
