### ISSUE TITLE
We could not find the `npm` command...

### ISSUE THREAD

**Issue by miguelpaz** [zeit/hyper#805]
We could not find the `npm` command... Make sure it's in $ Path

This is the message I got after downloading Hyperterm to Mac powerbook OS X El Capitan 10.11.12 and opening it. 

After when doing basic things like ls>

Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at WebContents.send (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:93:15)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:136:21)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:188:7)

**Comment by maxdeviant** [comment]
Do you have `npm` installed on your system already? It is currently not bundled with Hyper, so you'll need to have it installed and in your path.

**Comment by miguelpaz** [comment]
No I did not have it installed on this machine @maxdeviant. Thanks for the information.
