### ISSUE TITLE
hyper-news.now.sh is down

### ISSUE THREAD

**Issue by shime** [zeit/hyper#829]
I'm getting these error messages

```
Notification messages fetch error FetchError: request to https://hyper-news.now.sh failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/hrvoje/code/hack/hyper/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Checking for notification messages
```

And going to [https://hyper-news.now.sh/](https://hyper-news.now.sh/) returns 502.

**Comment by leo** [comment]
@rase- fixed it!

**Comment by joeblau** [comment]
I think it's back down.
