### ISSUE TITLE
Plugins typo breaks everything

### ISSUE THREAD

**Issue by brz0** [zeit/hyper#986]
Made an error in editing preferences, and now I can't use anything. I can't access the plugins file to change anything, and a new shell window gives this error with blank screen: 

Uncaught Exception:
Error: spawn Applications/MAMP/htdocs ENOENT
    at Object.exports._errnoException (util.js:1026:11)
    at Socket.<anonymous> (/Applications/Hyper.app/Contents/Resources/app/node_modules/child_pty/lib/child_pty.js:103:15)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

Would be good to have a "restore to default" option for when someone accidentally saves with some syntax error

-

Hyper 0.8.3
Electron 1.4.0
darwin x64 16.1.0

**Comment by stefanivic** [comment]
@brz0 you can go to your home directory ( usually something like C:\users\user\ or ~/ in unix OS ) and find the .hyper.js file and modify it.

**Comment by brz0** [comment]
Ended up doing that thanks, so I guess it's solved. Restore to default would be a nice feature though
